"""initial_schema

Revision ID: bcd52648b99e
Revises: 
Create Date: 2026-01-13 15:51:54.994565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcd52648b99e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('POSTGRES', 'MYSQL', 'MONGODB', 'REDIS', 'DYNAMODB', 'AURORA', name='databasetype'), nullable=False),
    sa.Column('cloud_provider', sa.Enum('AWS', 'GCP', 'AZURE', name='cloudprovider'), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.Enum('PRODUCTION', 'STAGING', 'DEVELOPMENT', name='environment'), nullable=False),
    sa.Column('health_status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', name='healthstatus'), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('storage_usage', sa.Float(), nullable=True),
    sa.Column('connections_active', sa.Integer(), nullable=True),
    sa.Column('connections_max', sa.Integer(), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('cost_trend', sa.Float(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('instance_type', sa.String(length=100), nullable=True),
    sa.Column('storage_size_gb', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_issues_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_databases_cloud_provider'), 'databases', ['cloud_provider'], unique=False)
    op.create_index(op.f('ix_databases_environment'), 'databases', ['environment'], unique=False)
    op.create_index(op.f('ix_databases_name'), 'databases', ['name'], unique=False)
    op.create_index(op.f('ix_databases_region'), 'databases', ['region'], unique=False)
    op.create_index(op.f('ix_databases_type'), 'databases', ['type'], unique=False)
    op.create_table('billing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('compute_cost', sa.Float(), nullable=True),
    sa.Column('storage_cost', sa.Float(), nullable=True),
    sa.Column('backup_cost', sa.Float(), nullable=True),
    sa.Column('data_transfer_cost', sa.Float(), nullable=True),
    sa.Column('other_cost', sa.Float(), nullable=True),
    sa.Column('compute_hours', sa.Float(), nullable=True),
    sa.Column('storage_gb', sa.Float(), nullable=True),
    sa.Column('data_transfer_gb', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('billing_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_records_billing_date'), 'billing_records', ['billing_date'], unique=False)
    op.create_index(op.f('ix_billing_records_database_id'), 'billing_records', ['database_id'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.Enum('DEPLOYMENT', 'CONFIG_CHANGE', 'SCALING', 'MIGRATION', 'MAINTENANCE', 'VERSION_UPGRADE', 'FAILOVER', name='changetype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('impact_score', sa.String(length=20), nullable=True),
    sa.Column('related_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_change_type'), 'change_events', ['change_type'], unique=False)
    op.create_index(op.f('ix_change_events_database_id'), 'change_events', ['database_id'], unique=False)
    op.create_index(op.f('ix_change_events_executed_at'), 'change_events', ['executed_at'], unique=False)
    op.create_table('cost_anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_type', sa.Enum('SPIKE', 'SUSTAINED_INCREASE', 'UNEXPECTED_CHARGE', name='costanomalytype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('baseline_amount', sa.Float(), nullable=False),
    sa.Column('deviation_percent', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('possible_causes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_anomalies_database_id'), 'cost_anomalies', ['database_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='issueseverity'), nullable=False),
    sa.Column('category', sa.Enum('PERFORMANCE', 'CAPACITY', 'AVAILABILITY', 'CONFIGURATION', 'COST', 'SECURITY', name='issuecategory'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='issuestatus'), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('related_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_services', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(), nullable=True),
    sa.Column('last_detected_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_category'), 'issues', ['category'], unique=False)
    op.create_index(op.f('ix_issues_database_id'), 'issues', ['database_id'], unique=False)
    op.create_index(op.f('ix_issues_severity'), 'issues', ['severity'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL', name='loglevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_entries_database_level_timestamp', 'log_entries', ['database_id', 'level', 'timestamp'], unique=False)
    op.create_index(op.f('ix_log_entries_level'), 'log_entries', ['level'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_database_name_timestamp', 'metrics', ['database_id', 'name', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_database_name_timestamp', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_level'), table_name='log_entries')
    op.drop_index('ix_log_entries_database_level_timestamp', table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_severity'), table_name='issues')
    op.drop_index(op.f('ix_issues_database_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_category'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_cost_anomalies_database_id'), table_name='cost_anomalies')
    op.drop_table('cost_anomalies')
    op.drop_index(op.f('ix_change_events_executed_at'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_database_id'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_change_type'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_index(op.f('ix_billing_records_database_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_billing_date'), table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_index(op.f('ix_databases_type'), table_name='databases')
    op.drop_index(op.f('ix_databases_region'), table_name='databases')
    op.drop_index(op.f('ix_databases_name'), table_name='databases')
    op.drop_index(op.f('ix_databases_environment'), table_name='databases')
    op.drop_index(op.f('ix_databases_cloud_provider'), table_name='databases')
    op.drop_table('databases')
    # ### end Alembic commands ###
