"""add_tenants_stacks_normalisation_unmapped_onboarding

Revision ID: 16320476fb3d
Revises: 
Create Date: 2026-04-13 20:43:58.788336

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '16320476fb3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzer_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyzer_name', sa.String(length=128), nullable=False),
    sa.Column('db_type', sa.Enum('elasticsearch', 'mysql', 'cassandra', 'postgres', name='dbtype'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('min_confidence_without_logs', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analyzer_name')
    )
    op.create_table('normalisation_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('grafana_cloud', 'datadog', name='sourcetype'), nullable=False),
    sa.Column('db_type', sa.Enum('elasticsearch', 'mysql', 'cassandra', 'postgres', name='dbtype'), nullable=False),
    sa.Column('raw_metric_name', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'db_type', 'raw_metric_name', name='uq_norm_source_db_raw')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyzer_log_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyzer_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=128), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('confidence_impact', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['analyzer_id'], ['analyzer_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyzer_metric_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyzer_id', sa.UUID(), nullable=False),
    sa.Column('canonical_metric_name', sa.String(length=255), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['analyzer_id'], ['analyzer_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('db_type', sa.Enum('elasticsearch', 'mysql', 'cassandra', 'postgres', name='dbtype'), nullable=False),
    sa.Column('source_type', sa.Enum('grafana_cloud', 'datadog', name='sourcetype'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('api_endpoint', sa.Text(), nullable=False),
    sa.Column('api_key_ref', sa.Text(), nullable=False),
    sa.Column('cluster_label_key', sa.String(length=128), nullable=True),
    sa.Column('has_metrics_adapter', sa.Boolean(), nullable=False),
    sa.Column('has_log_adapter', sa.Boolean(), nullable=False),
    sa.Column('has_metadata_adapter', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_successful_pull', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stack_id', sa.UUID(), nullable=True),
    sa.Column('cluster_id', sa.String(length=255), nullable=False),
    sa.Column('db_type', sa.Enum('elasticsearch', 'mysql', 'cassandra', 'postgres', name='dbtype'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('cloud_provider', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.Enum('healthy', 'degraded', 'critical', 'unknown', name='healthstatus'), nullable=False),
    sa.Column('last_metric_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_log_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_metric_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('stack_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('clusters_found', sa.Integer(), nullable=True),
    sa.Column('clusters_ready', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unmapped_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('stack_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('grafana_cloud', 'datadog', name='sourcetype'), nullable=False),
    sa.Column('db_type', sa.Enum('elasticsearch', 'mysql', 'cassandra', 'postgres', name='dbtype'), nullable=False),
    sa.Column('raw_metric_name', sa.Text(), nullable=False),
    sa.Column('sample_value', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyzer_capability_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('analyzer_id', sa.UUID(), nullable=False),
    sa.Column('runnable_status', sa.Enum('runnable', 'reduced', 'blocked', name='runnablestatus'), nullable=False),
    sa.Column('confidence_ceiling', sa.String(length=16), nullable=False),
    sa.Column('missing_primary', sa.Text(), nullable=True),
    sa.Column('missing_corroborating', sa.Text(), nullable=True),
    sa.Column('missing_log_signals', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyzer_id'], ['analyzer_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'analyzer_id', name='uq_capability_cluster_analyzer')
    )
    op.create_table('baseline_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('canonical_metric_name', sa.String(length=255), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('p95', sa.Float(), nullable=False),
    sa.Column('p99', sa.Float(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('std_dev', sa.Float(), nullable=False),
    sa.Column('window_type', sa.String(length=32), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('covers_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('covers_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'canonical_metric_name', 'window_type', name='uq_baseline_cluster_metric_window')
    )
    op.create_table('cluster_log_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=128), nullable=False),
    sa.Column('source_platform', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avg_count_per_hour', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'signal_type', name='uq_cluster_signal_type')
    )
    op.create_table('cluster_metric_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('source_metric_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'source_metric_name', name='uq_cluster_source_metric')
    )
    op.create_index('ix_cmr_cluster_canonical', 'cluster_metric_registry', ['cluster_id', 'canonical_name'], unique=False)
    op.create_table('log_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_platform', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_signals_cluster_type_window', 'log_signals', ['cluster_id', 'signal_type', 'window_start'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('analyzer_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'critical', 'unknown', name='healthstatus'), nullable=False),
    sa.Column('prev_status', sa.Enum('healthy', 'degraded', 'critical', 'unknown', name='healthstatus'), nullable=True),
    sa.Column('observed', sa.Text(), nullable=False),
    sa.Column('baseline_summary', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='confidencelevel'), nullable=False),
    sa.Column('metric_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_freshness', sa.Enum('fresh', 'delayed', 'gap', 'pending', name='datafreshness'), nullable=False),
    sa.Column('lag_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verdicts_cluster_analyzer_run', 'verdicts', ['cluster_id', 'analyzer_name', 'run_at'], unique=False)
    op.create_index('ix_verdicts_cluster_status', 'verdicts', ['cluster_id', 'status'], unique=False)
    op.create_table('llm_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verdict_id', sa.UUID(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('trigger_reason', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verdict_id')
    )
    op.create_table('verdict_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verdict_id', sa.UUID(), nullable=False),
    sa.Column('log_signal_id', sa.UUID(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('metric', 'log_signal', name='evidencesourcetype'), nullable=False),
    sa.Column('confidence_delta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_signal_id'], ['log_signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verdict_evidence')
    op.drop_table('llm_explanations')
    op.drop_index('ix_verdicts_cluster_status', table_name='verdicts')
    op.drop_index('ix_verdicts_cluster_analyzer_run', table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index('ix_log_signals_cluster_type_window', table_name='log_signals')
    op.drop_table('log_signals')
    op.drop_index('ix_cmr_cluster_canonical', table_name='cluster_metric_registry')
    op.drop_table('cluster_metric_registry')
    op.drop_table('cluster_log_registry')
    op.drop_table('baseline_profiles')
    op.drop_table('analyzer_capability_map')
    op.drop_table('unmapped_metrics')
    op.drop_table('onboarding_sessions')
    op.drop_table('clusters')
    op.drop_table('stacks')
    op.drop_table('analyzer_metric_requirements')
    op.drop_table('analyzer_log_requirements')
    op.drop_table('tenants')
    op.drop_table('normalisation_map')
    op.drop_table('analyzer_definitions')
    # ### end Alembic commands ###
