"""add_ingest_tokens_push_source_type

Revision ID: 52d12c2ab6bd
Revises: 7c334c5feefc
Create Date: 2026-04-14 16:22:37.967913

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '52d12c2ab6bd'
down_revision: Union[str, None] = '7c334c5feefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add 'push' to the sourcetype enum in PostgreSQL
    op.execute("ALTER TYPE sourcetype ADD VALUE IF NOT EXISTS 'push'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('stack_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingest_tokens')
    # ### end Alembic commands ###
