"""fix_baseline_profiles_cluster_id_to_string

Revision ID: 706c4de84963
Revises: 16320476fb3d
Create Date: 2026-04-13 21:47:21.182247

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '706c4de84963'
down_revision: Union[str, None] = '16320476fb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop FK first — Postgres won't ALTER TYPE while the constraint is live
    op.drop_constraint('baseline_profiles_cluster_id_fkey', 'baseline_profiles', type_='foreignkey')
    op.alter_column('baseline_profiles', 'cluster_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               postgresql_using='cluster_id::text',
               existing_nullable=False)
    op.create_index(op.f('ix_baseline_profiles_cluster_id'), 'baseline_profiles', ['cluster_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('baseline_profiles_cluster_id_fkey', 'baseline_profiles', 'clusters', ['cluster_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_baseline_profiles_cluster_id'), table_name='baseline_profiles')
    op.alter_column('baseline_profiles', 'cluster_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
