"""add_instance_id_to_verdicts

Revision ID: 7c334c5feefc
Revises: 706c4de84963
Create Date: 2026-04-14 11:07:24.572443

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7c334c5feefc'
down_revision: Union[str, None] = '706c4de84963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verdicts', sa.Column('instance_id', sa.String(length=255), nullable=True))
    op.drop_index('ix_verdicts_cluster_analyzer_run', table_name='verdicts')
    op.create_index('ix_verdicts_cluster_analyzer_instance_run', 'verdicts', ['cluster_id', 'analyzer_name', 'instance_id', 'run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verdicts_cluster_analyzer_instance_run', table_name='verdicts')
    op.create_index('ix_verdicts_cluster_analyzer_run', 'verdicts', ['cluster_id', 'analyzer_name', 'run_at'], unique=False)
    op.drop_column('verdicts', 'instance_id')
    # ### end Alembic commands ###
